version: '3.5'

services:

  db:
    image: postgres:16.1-alpine3.19
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    # порты нужно указывать, чтобы можно было подключиться через DBeaver
    ports:
      - 5432:5432

  backend:
    image: sivikgosh/backend_11:programs
    # build: ../funtech/
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  frontend:
    image: natashasolntseva/funtech_frontend:v1.12
    volumes:
      - static_value:/app/static/
      - frontend_static:/app/frontend_static/
    env_file:
      - ./.env
    depends_on:
      - backend    

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - frontend_static:/var/html/frontend_static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  db:
    external: true
  static_value:
  media_value:
  frontend_static:
