version: '3.5'

services:

  db:
    image: postgres
    container_name: db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../funtech/
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../funtech:/app
    ports:
      - 8000:80
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db

  # frontend:
  #   depends_on:
  #     - backend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value:
