version: '3.5'

services:

  db:
    image: postgres:16.1-alpine3.19
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: sivikgosh/backend_11
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../funtech/:/app/
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  frontend:
    image: natashasolntseva/funtech_frontend
    volumes:
      - static_value:/app/static/
      - frontend_static:/app/frontend_static/
    env_file:
      - ./.env
    depends_on:
      - backend    

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - frontend_static:/var/html/frontend_static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  db_value:
  static_value:
  media_value:
  frontend_static:
