# Generated by Django 4.1.7 on 2024-04-14 13:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('mobile_number', models.PositiveSmallIntegerField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('employment', models.CharField(max_length=100, null=True, verbose_name='Место работы')),
                ('position', models.CharField(max_length=100, null=True, verbose_name='Должность')),
                ('experience', models.CharField(choices=[('NO_EXP', 'Нет опыта'), ('ONE_YEAR', 'От 1 года'), ('THREE_YEARS', 'От 3 лет'), ('FIVE_YEARS', 'От 5 лет')], max_length=255, null=True, verbose_name='Опыт работы')),
                ('preferred_format', models.CharField(choices=[('OFFLINE', 'Оффлайн'), ('ONLINE', 'Онлайн')], max_length=255, null=True, verbose_name='Предпочитаемый формат')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('last_name',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='текст соглашения')),
                ('is_required', models.BooleanField(verbose_name='отметка обязательное/необязательное')),
            ],
            options={
                'verbose_name': 'соглашение',
                'verbose_name_plural': 'соглашения',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'направления',
                'default_related_name': 'expertises',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'стек',
                'verbose_name_plural': 'стек',
                'default_related_name': 'stack_items',
            },
        ),
        migrations.CreateModel(
            name='UserExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.expertise', verbose_name='Направление')),
                ('stack', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userExper', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'направление пользователя',
                'verbose_name_plural': 'направления пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signed', models.BooleanField(null=True, verbose_name='cостояние соглашения')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.agreement', verbose_name='соглашение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'соглашение пользователя',
                'verbose_name_plural': 'соглашения пользователя',
                'default_related_name': 'user_agreements',
            },
        ),
        migrations.AddField(
            model_name='expertise',
            name='stacks',
            field=models.ManyToManyField(through='users.UserExpertise', to='users.stack'),
        ),
        migrations.AddConstraint(
            model_name='useragreement',
            constraint=models.UniqueConstraint(fields=('user', 'agreement'), name='unique_agreement'),
        ),
    ]
