# Generated by Django 4.1.7 on 2024-04-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpertise',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exper', to='users.expertise', verbose_name='Направление'),
        ),
    ]
