# Generated by Django 5.0.3 on 2024-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agreement_expertise_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='stack',
            constraint=models.UniqueConstraint(fields=('name', 'expertise'), name='unique_stack'),
        ),
    ]
