# Generated by Django 4.1.7 on 2024-04-13 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date_time', models.DateTimeField(null=True, verbose_name='Дата и время')),
                ('max_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное кол-во участников')),
                ('information', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('OFFLINE', 'Оффлайн'), ('ONLINE', 'Онлайн')], max_length=255, verbose_name='Тип')),
                ('event_format', models.CharField(blank=True, choices=[('CONFERENCE', 'Конференция'), ('MEETUP', 'Митап'), ('NETWORKING', 'Нетворкинг'), ('EXCURSION', 'Экскурсия')], max_length=255, verbose_name='Формат')),
                ('activity_status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE_EVENT', 'Активное мероприятие')], max_length=255, verbose_name='Состояние')),
                ('wallpaper', models.ImageField(blank=True, upload_to=events.models.get_upload_event_wallpaper_path, verbose_name='Обои')),
                ('video', models.URLField(blank=True, verbose_name='Ссылка на видеозапись')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('builing', models.CharField(max_length=255, verbose_name='Место')),
                ('metro_station', models.CharField(blank=True, max_length=255, verbose_name='Станция метро')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('file', models.ImageField(blank=True, upload_to=events.models.get_upload_event_photos_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date_time', models.DateTimeField(null=True, verbose_name='Дата и время')),
                ('information', models.TextField(max_length=1000, verbose_name='Описание')),
                ('material', models.FileField(upload_to=events.models.get_upload_material_path, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speaker_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('job', models.CharField(max_length=255, verbose_name='Позиция')),
                ('avatar', models.ImageField(blank=True, upload_to=events.models.get_upload_speaker_avatar_path, verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('user_event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('agree', models.BooleanField(verbose_name='Согласен')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
            },
        ),
    ]
