# Generated by Django 4.1.7 on 2024-04-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
    ]
