# Generated by Django 4.1.7 on 2024-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='qr_code',
            field=models.CharField(max_length=50, null=True, verbose_name='QR код'),
        ),
    ]
