# Generated by Django 5.0.3 on 2024-04-04 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('number_of_paricipants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Число участников')),
                ('information', models.CharField(max_length=200, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('OFFLINE', 'offline'), ('ONLINE', 'online')], max_length=255, verbose_name='Тип')),
                ('event_format', models.CharField(choices=[('CONFERENCE', 'conference'), ('MEETUP', 'meetup '), ('NETWORKING', 'networking'), ('EXCURSION', 'excursion')], max_length=255, verbose_name='Формат')),
                ('theme', models.CharField(choices=[('PROGRAMMING', 'programming'), ('DESIGN', 'design '), ('MANAGEMENT', 'management'), ('MARKETING', 'marketing'), ('ANALYTICS', 'analytics'), ('BUSINESS', 'business'), ('OTHER', 'other')], max_length=255, verbose_name='Тематика')),
                ('program_time', models.TimeField(verbose_name='Время')),
                ('program_name', models.CharField(max_length=255, verbose_name='Название')),
                ('program_speaker', models.CharField(max_length=255, verbose_name='Докладчик')),
                ('program_information', models.TextField(max_length=1000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('REGISTRATION_OPEN', 'registration_open'), ('REGISTRATION_CLOSE', 'registration_close'), ('FINISHED', 'finished')], max_length=255, verbose_name='Статус')),
                ('activity_status', models.CharField(choices=[('DRAFT', 'draft'), ('ACTIVE_EVENT', 'active_event')], max_length=255, verbose_name='Состояние')),
            ],
        ),
    ]
