# Generated by Django 5.0.3 on 2024-04-05 16:04

import django.core.validators
import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('number_of_paricipants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Число участников')),
                ('information', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('OFFLINE', 'Оффлайн'), ('ONLINE', 'Онлайн')], max_length=255, verbose_name='Тип')),
                ('event_format', models.CharField(blank=True, choices=[('CONFERENCE', 'Конференция'), ('MEETUP', 'Митап'), ('NETWORKING', 'Нетворкинг'), ('EXCURSION', 'Экскурсия')], max_length=255, verbose_name='Формат')),
                ('status', models.CharField(choices=[('REGISTRATION_OPEN', 'Регистрация открыта'), ('REGISTRATION_CLOSE', 'Регистрация закрыта'), ('FINISHED', 'Завершено')], max_length=255, verbose_name='Статус')),
                ('activity_status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE_EVENT', 'Активное мероприятие')], max_length=255, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='Matetial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=events.models.get_upload_path, verbose_name='Файл')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='events.event')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('time', models.TimeField(verbose_name='Время')),
                ('speaker', models.CharField(max_length=255, verbose_name='Докладчик')),
                ('information', models.TextField(max_length=1000, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='events.event')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='EventTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='events.event')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.theme')),
            ],
            options={
                'verbose_name': 'Тематика мероприятия',
                'verbose_name_plural': 'Тематики мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='Сcылка')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='events.event')),
            ],
            options={
                'verbose_name': 'Видеозапись',
                'verbose_name_plural': 'Видеозаписи',
            },
        ),
    ]
