# Generated by Django 5.0.3 on 2024-04-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='program_information',
        ),
        migrations.RemoveField(
            model_name='event',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='program_speaker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='program_time',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('time', models.TimeField(verbose_name='Время')),
                ('speaker', models.CharField(max_length=255, verbose_name='Докладчик')),
                ('information', models.TextField(max_length=1000, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='events.event')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
