# Generated by Django 5.0.3 on 2024-04-06 13:23

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('builing', models.CharField(max_length=255, verbose_name='Адрес')),
                ('metro_station', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='number_of_paricipants',
            new_name='number_of_participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='event',
            name='wallpaper',
            field=models.ImageField(null=True, upload_to=events.models.get_upload_wallpaper, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=models.SET('location.building'), to='events.location'),
        ),
    ]
