# Generated by Django 5.0.3 on 2024-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='builing',
            field=models.CharField(max_length=255, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='location',
            name='metro_station',
            field=models.CharField(blank=True, max_length=255, verbose_name='Станция метро'),
        ),
    ]
