# Generated by Django 5.0.3 on 2024-04-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_remove_event_program_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_format',
            field=models.CharField(blank=True, choices=[('CONFERENCE', 'conference'), ('MEETUP', 'meetup '), ('NETWORKING', 'networking'), ('EXCURSION', 'excursion')], max_length=255, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='event',
            name='information',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='EventTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.theme')),
            ],
        ),
    ]
