# Generated by Django 5.0.3 on 2024-04-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_theme_remove_event_theme_alter_event_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtheme',
            options={'verbose_name': 'Тематика мероприятия', 'verbose_name_plural': 'Тематики мероприятий'},
        ),
    ]
