# Generated by Django 5.0.3 on 2024-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventtheme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtheme',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='events.event'),
        ),
    ]
