name: Run TODO to Issue

on: [push]

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        with:
          AUTO_ASSIGN: true
